sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t mitanjalic/fib-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mitanjalic/fib-complex-test npm run test

after_success:
  - docker build -t mitanjalic/fib-client ./client
  - docker build -t mitanjalic/fib-nginx ./nginx
  - docker build -t mitanjalic/fib-server ./server
  - docker build -t mitanjalic/fib-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push mitanjalic/fib-client
  - docker push mitanjalic/fib-nginx
  - docker push mitanjalic/fib-server
  - docker push mitanjalic/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fib-docker
  env: FibDocker-env
  bucket_name: elasticbeanstalk-us-east-2-643889700418
  bucket_path: docker-fib
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
